version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    hostname: postgres
    expose:
      - "5433"
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=BB-DB
  api:
    build:
      context: . #current root foler
      dockerfile: Dockerfile #find dockerfile
    image: samanthatb1/bead-bash-orders  ## goes to your repository on Docker Hub
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/BB-DB?sslmode=disable
      - SERVER_ADDRESS=0.0.0.0:8080
      - DB_DRIVER=postgres
      - ENVIRONMENT=production
    depends_on:
      - postgres
    entrypoint: ["sh", "/app/start.sh"] #ensure postgres finishes before api
    command: ["/app/main"]