// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Order struct {
	OrderID   int64  `json:"order_id"`
	AccountID int64  `json:"account_id"`
	Username  string `json:"username"`
	FullName  string `json:"full_name"`
	// must be positive
	PurchaseAmount   float64 `json:"purchase_amount"`
	PurchasedItem    string  `json:"purchased_item"`
	ShippingLocation string  `json:"shipping_location"`
	Currency         string  `json:"currency"`
	DateOrdered      string  `json:"date_ordered"`
}

type User struct {
	ID          int64     `json:"id"`
	Username    string    `json:"username"`
	FullName    string    `json:"full_name"`
	TotalOrders int64     `json:"total_orders"`
	CreatedAt   time.Time `json:"created_at"`
}
